---
ID: "c29a7ecf-dbbf-4184-a674-60123e132278"
Parent: "324b4131-c845-486b-a62b-bfe65d62b017"
Template: "324b4131-c845-486b-a62b-bfe65d62b017"
Path: /sitecore/templates/Gymster/Data Templates/Carousel Slide/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230502T050157Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
