---
ID: "23a2654c-50ed-475b-9a4f-f5a6dc4a511a"
Parent: "1229653a-2e62-4c1e-96fe-6f6362138d8b"
Template: "1229653a-2e62-4c1e-96fe-6f6362138d8b"
Path: /sitecore/templates/Gymster/Data Templates/Hero/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230501T052331Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
