---
ID: "ba7e43c0-25b7-4bff-adbe-40c895910ed2"
Parent: "ca655637-227e-4573-b00d-d26963cc363e"
Template: "e28a1892-f628-4dcf-aced-6b2b56fe4f1e"
Path: /sitecore/content/Gymster/Home/Trainers
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230502T134314Z
    - ID: "f22370fd-63f8-471f-beed-d0195fec2991"
      Hint: Navigation Title
      Value: Trainers
